### ISSUE TITLE
Missing ) 

### ISSUE THREAD

**Issue by RobThree** [s-marley/CarLights#1]
Hey! [Nice video](https://www.youtube.com/watch?v=gqaCwqRQ3gE)!

I decided to have a look at your code and happened to spot [this missing `)`](https://github.com/s-marley/CarLights/blob/8cca43a49089d5e8dcca61c294a7f79612558379/CarInterface.ino#L42). I'm pretty sure this won't compile 😉

**Comment by s-marley** [comment]
Wow, how did that happen?!

Thanks for letting me know, I'll fix it now :)
